### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by ionelmc** [noirbizarre/bumpr#4]
I get this if I run `bumpr` and there's no conf file (I'm assuming that's the cause):
```
Traceback (most recent call last):
  File "/usr/local/bin/bumpr", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bumpr/__init__.py", line 32, in main
    releaser = Releaser(config)
  File "/usr/local/lib/python2.7/dist-packages/bumpr/releaser.py", line 26, in __init__
    with open(config.file) as f:
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by ionelmc** [comment]
It should at least give some pretty message explaining the problem.
